### ISSUE TITLE
Zaznaczenie - kasowanie

### ISSUE THREAD

**Issue by blazejbiernacik** [hightest/angular-tables#1]
Możliwość kasowania zaznaczenia.

**Comment by Nowicki** [comment]
Dziękujemy za zgłoszenie. Z przykrością informujemy, iż podana funkcja nie może zostać wprowadzona do aplikacji, jednakże jest rozwiązanie, które można zastosować:

```
angular.forEach(data, function(value) {
    if (value.$htTable && value.$htTable.selected) {
        value.$htTable.selected = false;
    }
});
```
